name: Deployment

on:
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      # uses: hashicorp/setup-terraform@v2
      uses: opentofu/setup-opentofu@v1

    - name: Terraform Init
      run: tofu init -backend=false

    - name: Terraform Apply
      run: tofu apply -no-color -auto-approve

    - name: Export terraform outputs
      id: tfout
      run: |
        terraform output
