name: Terraform Checks

on:
  # workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  Terraform-Checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Setup Terraform
      # uses: hashicorp/setup-terraform@v2
      uses: opentofu/setup-opentofu@v1

    - name: Terraform Init
      id: Init
      run: tofu init

    - name: Terraform fmt
      id: fmt
      run: tofu fmt -check

    - name: Terraform Validate
      id: validate
      run: tofu validate -no-color

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
